spring.application.name=spring-boot-101

# JDBC Properties
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

# SpringDoc OpenAPI 3 configuration
#springdoc.swagger-ui.enabled=true
#springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/my-ui.html
#springdoc.api-docs.path=/v3/api-docs